<?php

namespace MVC\Controllers;

//use MVC\Controllers;

class AboutController extends Controller
{

    public static function createView()
    {

        parent::createView(); // TODO: Change the autogenerated stub
    }
}